module.exports = {
    MessageBoard: require('./user/messageBoard'),
    Admin: require('./admin/admin'),
    AdminSession: require('./admin/adminSession'),
    Challenge: require('./admin/challenge'),
    User: require('./user/user'),
    UserSession: require('./user/session'),
    NflGame: require('./nflPickEm/nflGame'),
    NflTeam: require('./nflPickEm/nflTeam'),
    MlbPickEm: require('./mlbPickEm'),
    MlbGame: require('./mlbPickEm/mlbGame'),
    MlbTeam: require('./mlbPickEm/mlbTeam'),
    NbaGame: require('./nbaPickEm/nbaGame'),
    NbaTeam: require('./nbaPickEm/nbaTeam'),
    NbaPlayoffGame: require('./nbaPlayoffPickEm/nbaPlayoffGame'),
    NbaPlayoffTeam: require('./nbaPlayoffPickEm/nbaPlayoffTeam'),
    Golfer: require('./masters/golfer'),
    PLGame: require('./premierLeaguePickEm/pLGame'),
    PLTeam: require('./premierLeaguePickEm/pLTeam')
}